[package]
name = "sora"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
thiserror = "1.0.63"
uuid = { version = "1.10.0", features = ["v7"] }

[dev-dependencies]
rstest = "0.22.0"
