services:
  database:
    image: postgres:16.4-alpine3.20
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    ports:
      - "0.0.0.0:5432:5432/tcp"
