[package]
name = "sora_core"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { workspace = true }
thiserror = { workspace = true }
uuid = { workspace = true, features = ["v7"] }

[dev-dependencies]
rstest = { workspace = true }
